### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by MrWelsch** [bilalekremharmansa/SceneBuilderVSCodeExtension#7]
Hey, so I configured scenebuilder.home to /mnt/c/ProgramFiles/SceneBuilder/SceneBuilder.exe.
Whenever I try to open a fxml file the error message shown below pops up.

![grafik](https://user-images.githubusercontent.com/45096895/102538366-78319500-40ac-11eb-9211-eb6eff091014.png)

`java.io.FileNotFoundException: C:\home\kuma\Code\kochbuch\src\main\resources\Knuth\primary.fxml (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.readContentFromURL(FXOMDocument.java:389)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:385)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:665)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:510)
	at com.oracle.javafx.scenebuilder.app.AppPlatform$MessageBoxDelegate.lambda$messageBoxDidGetMessage$0(AppPlatform.java:180)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

There are no Issues when opening the same file directly in SceneBuilder.

**Comment by bilalekremharmansa** [comment]
It seems that SceneBuilder could not find "primary.fxml"  file properly.

I've noticed that  you are trying to open this file ```C:\home\kuma\Code\kochbuch\src\main\resources\Knuth\primary.fxml```, and executable scene builder path is ```/mnt/c/ProgramFiles/SceneBuilder/SceneBuilder.exe.```.  Are you using WSL(Windows Subsystem for Linux) ? I am not sure but this might cause to actual problem. I don't know much how WSL works but it looks like two different filesystem exist. 

Probably, scene builder could open this file if vs code could've accessed with the following path:```/mnt/home/kuma/Code/kochbuch/src/main/resources/Knuth/primary.fxml```.
